name: Nightly Snap Post

on:
  schedule:
    - cron: "0 16 * * *"   # 9:30 PM IST (UTC+5:30)
  workflow_dispatch: {}

permissions:
  contents: write   # commit the generated image to images/

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow cryptography
      - name: Generate & post to Snapchat
        env:
          # OpenAI
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
          IMAGE_SIZE:      "1024x1024"

          # Snapchat
          SNAP_ACCESS_TOKEN: ${{ secrets.SNAP_ACCESS_TOKEN }}   # MUST start with:  Bearer <token>
          SNAP_PROFILE_ID:   ${{ secrets.SNAP_PROFILE_ID }}

          # GitHub (repo info + built-in token)
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO:    ${{ github.repository }}
          GITHUB_BRANCH:  ${{ github.ref_name }}
          IMAGES_FOLDER:  images/

          # Optional footer text
          CAPTION_FOOTER: "Discount Smokes"
        run: python generate_and_post_snap.py
